### PR TITLE
scfinder: add plotting utility script

### PR DESCRIPTION
**Pull request by jenrandrews**
This adds a plotting/emailing utility script (.py) and an example of its configuration file (_config.py), plus a wrapper script (.sh) that can be used to run the plotting script using the scalert module.

The plotting script is still pretty rough, but is designed to either be run standalone for offline FinDer library results (log file and data_ directory) or SeisComP (calling the db and using the data_ directory).

### CODE REVIEW

**Comment by FMassin** [comment]
HI @jenrandrews !

Very nice! I kind of forgot to check with you if the license selected by SED is fine with you? Would you agree to adapt (adjust with you authorship) something like this below for each of these contributions ?

https://github.com/SED-EEW/SED-EEW-SeisComP-contributions/blob/aaf03627b15bbb700e876afa818bc5d937689194/apps/eew/sceewlog/sceewdump.py#L1-L19

**Comment by jenrandrews** [comment]
Yes sure, will do...

**Comment by FMassin** [comment]
Thanks! I'm struggling to test. Ican't get anything but the attached. 
[makeFinDerPlot_220919T102749.log](https://github.com/SED-EEW/SED-EEW-SeisComP-contributions/files/9598701/makeFinDerPlot_220919T102749.log)

How is it supposed to know where the FinDer PGA (`data_*` files) are logged into?

**Comment by jenrandrews** [comment]
Hi Fred, 
If you're running using SeisComP, the PGA data file location (and most other variables) need to be set in makeFinDerPlot_config.py. The data_* directory is the variable 'pga_dir_loc'. (If you're running completely standalone you set the log file and the data_* directory on the command line with -log and -datadir.)
Looking at your log file though, the problem isn't with the data_* files, it's with the call to scxmldump, which isn't returning valid XML. Have you tried running on the command line to see the return? The script is trying:
scxmldump --config-file <scxmldump config file> -m -E smi:ch.ethz.sed/sc20d/Event/2022rvutnn
Note that the scxmldump.cfg is also set using makeFinDerPlot_config.py using the variable scxmldump_cfg.
Is this running through scalert, or from the command line?
Cheers,
Jen

**Pull request merged**
