### PR TITLE
[sceewenv] Replace boost::bind with std::bind

### PR DESCRIPTION
**Pull request by gempa-jabe**

### CODE REVIEW

**Comment by FMassin** [comment]
Hi @gempa-jabe 

Thanks a lot for your suggestion. It looks like less dependency to boost, I like the idea.

Unfortunately this break my build procedure (see checks below) while it was still ok [on master](https://github.com/SED-EEW/SED-EEW-SeisComP-contributions/actions/runs/3472615197)... Any help?

Cheers 

Fred

**Comment by FMassin** [comment]
Ok I can see you're off fixing it in sed-contrib, I guess I'll wait for that to try again :)

**Comment by gempa-jabe** [comment]
You can try again right now.

**Comment by FMassin** [comment]
@luca-s @sheimers, @gempa-jabe is trying to fix [sed-contrib ](https://github.com/swiss-seismological-service/sed-SeisComP-contributions)with latest seiscomp but there are still [issues left](https://github.com/SED-EEW/SED-EEW-SeisComP-contributions/actions/runs/3486918587/jobs/5833968976). Any help?

**Pull request merged**
